version: '3'

networks:
  api-network:

services: 
  php-cli:
    build:
      context: ./php-cli
    tty: true
    volumes:
      - ../:/var/www
    networks: 
      - api-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "51321:80"
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - api-network
    
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www
    networks:
      - api-network
  
  database:
    build: 
      context: ./mysql
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "my-super-secret-password"
      MYSQL_DATABASE: "user-database"
      MYSQL_USER: "db-user"
      MYSQL_PASSWORD: "user-password"
    volumes:
      - ../database:/var/lib/mysql # make sure this directory exists!

  adminer:
    build: 
      context: ./adminer
    depends_on:
      - database
    restart: always
    ports: 
      - "51322:8080"